apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyn-proxy-deployment
  labels:
    app: dyn-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyn-proxy
  template:
    metadata:
      labels:
        app: dyn-proxy
    spec:
      containers:
        - name: proxy-server
          image: whaleeye/dyn-proxy:latest
          ports:
            - containerPort: 8899
